### ISSUE TITLE
Modify CSS and Dashboard Theme 

### ISSUE THREAD

**Issue by kajal-alpha** [OpenCodeFoundation/asset-manager#19] opened 2018-04-19 03:54 UTC
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

There are some issues in bootstrap theme. 900 plus error found in css file. there are lots of unnecessary code/file.

## Expected behavior

There should not be unnecessary code/file.

**Comment by ratanparai** [comment] 2018-05-29 19:40
I am closing this issue as I think it has already been fixed. If you think the issue is still there, please reopen the issue.

**Closed by ratanparai** 2018-05-29 19:40 UTC
Labels: bug
